[app]
name = "cmdb"
key  = "this is your app key"

[app.http]
host = "127.0.0.1"
port = "8060"

[app.grpc]
host = "127.0.0.1"
port = "18060"




[mysql]
host = "192.168.10.10"
port = "3306"
database = "cmdb"
username = "ops"
password = "Ren910202."



[log]
level = "debug"
path = "logs"
format = "text"
to = "stdout"